# Generated by Django 4.1.4 on 2023-01-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_booking_no_of_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('same', models.CharField(max_length=255)),
                ('no_guest', models.IntegerField()),
            ],
        ),
    ]
