# Generated by Django 4.1.4 on 2023-01-22 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_newbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newbook',
        ),
    ]
